#!/bin/sh

set -e -u

DUMMY_PRINTER_NAME=adt-printer0

# Create dummy printer
/usr/sbin/lpadmin -p $DUMMY_PRINTER_NAME -E -v file:///dev/null

# Print the default testprint to it, get request id
rid=$(/usr/bin/lp -d $DUMMY_PRINTER_NAME ../../data/default-testpage.pdf | sed -e 's/^.*request id is \(.*\) (.*)$/\1/g')

# Wait for the print to finish
while $(/usr/bin/lpstat | grep "^$rid "); do
    :
done

# Delete it
/usr/sbin/lpadmin -x $DUMMY_PRINTER_NAME
