#!/bin/sh
set -e
# Automatically added by dh_installinit/13.3.4ubuntu2
if [ "$1" = "purge" ] ; then
	update-rc.d cups-browsed remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.3.4ubuntu2
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.3.4ubuntu2
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'cups-browsed.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'cups-browsed.service' >/dev/null || true
		deb-systemd-helper unmask 'cups-browsed.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/3.0.3-0ubuntu1
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.sbin.cups-browsed" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.sbin.cups-browsed" || true
    rm -f "/etc/apparmor.d/force-complain/usr.sbin.cups-browsed" || true
    rm -f "/etc/apparmor.d/local/usr.sbin.cups-browsed" || true
    rm -f /var/cache/apparmor/*/"usr.sbin.cups-browsed" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
